service: user-service-sls
frameworkVersion: "4"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "prod"
  region: ap-south-1
  httpApi:
    cors: true

custom:
  stage: "prod"
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002

functions:
  signup:
    handler: app/handler.SignUp
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post
  create-profile:
    handler: app/handler.CreateProfile
    events:
      - httpApi:
          path: /user
          method: post
  edit-profile:
    handler: app/handler.EditProfile
    events:
      - httpApi:
          path: /user
          method: put
  get-profile:
    handler: app/handler.GetProfile
    events:
      - httpApi:
          path: /user
          method: get
  # Cart Section
  create-cart:
    handler: app/handler.CreateCart
    timeout: 20
    events:
      - httpApi:
          path: /cart
          method: post
  edit-cart:
    handler: app/handler.EditCart
    timeout: 20
    events:
      - httpApi:
          path: /cart/{id}
          method: put
  get-cart:
    handler: app/handler.GetCart
    timeout: 20
    events:
      - httpApi:
          path: /cart
          method: get
  delete-cart:
    handler: app/handler.DeleteCart
    timeout: 20
    events:
      - httpApi:
          path: /cart/{id}
          method: delete

plugins:
  - serverless-offline
  # - serverless-plugin-typescript
  - serverless-plugin-optimize

package:
  individually: true
